name: bat man test

on:
  push:
    branches: main 
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
    - name: Setup Node.js
      uses: actions/setup-node@v4 
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install Dependencies
      run: yarn install 
    - name: Run Syntax & Build Test
      run: node --check asura.js 
